### ISSUE TITLE
Add a way to place the large search box on paths that result in a 404 error

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#123]
Clients have requested the ability to place a large search box on the 404 page.

We want to make sure that there are no negative impacts on performance that could increase our susceptibility to DOS attacks.

**Comment by kevincrafts** [comment]
In talking with Jo this week, she mentioned that this might be able to serve part of the use case of the cu_libraries_bundle that is currently being used on /policies in that a large search block could be placed on other pages to encourage people to search for content.

**Comment by kevincrafts** [comment]
James, Jo, and I discussed adding another search form block that can be placed on other pages. Examples of this would include:
1. A search form that could be placed on custom 404 pages
2. A prominent search form on the sites front page for sites where searching is the recommended way to find content

**Comment by AlanBCole** [comment]
cu libraries bundle: https://github.com/CuBoulder/custom_culibraries_bundle

**Comment by kevincrafts** [comment]
Seems like we lost part of the original scope of the ticket. We had added and deployed the search box, however, the part that is still missing is the ability to put it on a path which results in a 404.

The problems we run into with this are:
1. Context can't be used because we don't have a condition for a 404 error.  Even if you create a custom page for the 404 error, you cannot use that path for the condition because when you get a 404, you are still on that path that resulted in the 404.  You are NOT redirected to the path of your custom page, so the condition will always fail.
2. You can't use the page layout tools, because the module will load the node of the custom 404 page, which is only the node content, not its corresponding layout.

**Comment by kevincrafts** [comment]
I think we should consider this module: https://www.drupal.org/project/context_error
