### ISSUE TITLE
Managing Users: Removing User Role

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express_mono#135]
The criteria we use to pull user data for email communications is whether the user has a role assigned to them or not. Users without roles do not have emails generated in the returned list of users in Lil Shrugger. Currently site owners do not have the ability to remove the user's role only block a user so we will continue to pull blocked users' emails for our communications list.

It would be better if the disable account option also removed any user roles assigned to the account.

**Comment by kevincrafts** [comment]
Because we altered the role form to be radio buttons instead of checkboxes, removing the core role from a user is more difficult.  

I suggest we could add an additional submit button in the same alter hook that would remove all roles from the user.  Even blocking a user does not remove roles, and we use these role assignments to create email lists for our communications.
