### ISSUE TITLE
Write update hook to remove roles from former developers

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#277]
Need to make sure that we don't accidentally delete any content

**Comment by jcsparks** [comment]
We should remove roles rather than removing users and assigning content to the anonymous user for a couple of reasons.  First, by removing the user you'll destroy any history associated with the user tied to content.  Second, we should be avoiding the pattern of trying to solve an HR issue with technology.  There may be an exception if we have a disgruntled employee but in general we shouldn't be trying to solve that potential issue by deleting accounts.  Former employees should still be trusted not to violate the terms-of-use of their IdentiKey or standard computing laws.

**Comment by cathysnider** [comment]
And a reminder of how things currently work on Web Express:
An IdentiKey holder cannot login to a Web Express site unless they have a role on that site. That default functionality was removed and replaced with the External Invite functionality. An Identikey holder used to have a role but no longer does gets the same message as someone who never had a role:

"You do not have permission to edit this site. If you received an email invitation, please use the link provided."

![Screen Shot 2019-09-23 at 12 00 40 PM](https://user-images.githubusercontent.com/638275/65451159-d618f380-ddfb-11e9-9947-2c4f24916a8e.png)

To note: They can't actually because the invite system checks to see if they have an account. They do; it's just blank. For them, the Site Owner must go to admin/people/promote and assign a role to them.

**Comment by jcsparks** [comment]
There is an argument that by leaving the former users we're passing-the-buck to the site owners who, in trying to practice prudent user maintenance, will delete those users without roles and end up deleting their content anyway causing the very issue we're trying to avoid.

**Comment by cathysnider** [comment]
A Site Owner does not have the ability to delete content.  They can:
 - [ ]  Disable the account and keep its content.
 - [ ]  Disable the account and unpublish its content.
 - [ ]  Delete the account and make its content belong to the Anonymous user.

They can't delete nodes but they can delete history.
