### ISSUE TITLE
Add a color inherit .button-ghost class

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express_mono#315]
Problems exist with some of the button colors:

https://www.colorado.edu/demos/cathys-sandbox/color-checks/colored-block-sections-other-blocks

Examples:

![Screen Shot 2019-10-07 at 10 32 58 AM](https://user-images.githubusercontent.com/638275/66330551-ddf19100-e8ed-11e9-98d7-4abc58137169.png)

![Screen Shot 2019-10-07 at 10 32 41 AM](https://user-images.githubusercontent.com/638275/66330569-e77af900-e8ed-11e9-80d0-5108fa80512c.png)

**Comment by kevincrafts** [comment]
James and I talked over the issue this afternoon and decided that instead of presenting the read more as a button, we will present it as a regular link. By doing this, the color of the link will just be the same color of the headlines, and the read more button will not be competing with the actual headline links of the content, which should be more important.

**Comment by kevincrafts** [comment]
![Screen Shot 2019-10-09 at 2 36 03 PM](https://user-images.githubusercontent.com/349713/66518324-29e53700-eaa2-11e9-91d8-7d540969d338.png)

**Comment by kevincrafts** [comment]
Ran this by Jo and she expressed some concerns about this design change so I'm going to work on 2-3 mockups for this before we start changing code.
