### ISSUE TITLE
Import cu_mega_menu_bundle

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express_mono#48]
https://github.com/CuBoulder/cu_mega_menu_bundle

**Comment by jwfuller** [comment]
From @kevincrafts:

As a So/SE I would like a configurable mega menu that would include links and minimal content that would appear upon clicking/tapping a main menu item.

![screen shot 2018-12-03 at 4 08 56 pm](https://user-images.githubusercontent.com/349713/49407421-c8339e00-f715-11e8-8289-96ae9de52b50.png)
![screen shot 2018-12-03 at 4 08 50 pm](https://user-images.githubusercontent.com/349713/49407422-c8cc3480-f715-11e8-826c-a1392996c1af.png)

**Comment by jwfuller** [comment]
From @cathysnider 

## Describe the bug
Developers and Site Owners can create Mega Menus. Administrators cannot. This is an oversight in permissions.
When an administrator goes to /admin/structure/mega-menu, they get an 'Access Denied' message.

## Expected behavior
Administrators be able to create and edit Mega Menus


Verified May 14 2019

Administrator role is denied access to /admin/structure/mega-menu 

![megaMenus](https://user-images.githubusercontent.com/638275/57717010-7c2b4480-7637-11e9-97b5-2f5b4f66cd25.jpg)
