### ISSUE TITLE
Articles by Person block causes an error if there is more than 1 byline term linked to the same person node

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_mono#554]
The way this might come about is if someone changes their name on the person node (for example, adding their middle name), then the next time they write and article and use the byline field with their new name, a new term is added and linked to the person node, resulting in 2 terms linked to the same node id.  The query in the Articles by Person block will fail and give a sql error.

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller What modules need to be enabled in order to verify and work on this bug?

**Comment by AlanBCole** [comment]
@kevincrafts @jwfuller I have not been able to reproduce this. So far this is what I have done:

1. created a person with the Person content type
    - the person has first and last names
2. created an article
    - in the byline section, accessed by clicking the "byline" tab under the WYSIWYG editor, I typed the newly person's first and last name as "firstname lastname"
3. I saved and looked at the article
    - the article has the author's name as a link that correctly links to the author's Person page
4. I went back to the new person's Person page and edited the name so that the first name contains the middle name as "firstname middlename" and saved the change
5. Created a new article as before but this time used the person's newly adjusted name in the byline
6. Looked at the new article:
    - author showed as a link that correctly links to the author's Person page.
7. Looked at the old article:
    - author showed as a link with the previous person's name (no middle name) that still correctly links to the author's Person page.
    - the author's Person page shows the most recently saved name.

Am I missing something or am I not using the correct block. I have not found an Article by Person block...

**Comment by jwfuller** [comment]
@AlanBCole https://websupport.colorado.edu/article/249-articles-by-person-block
