### ISSUE TITLE
Overridden feature 'CU Google Analytics'

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#603]
Commonly overridden feature, guessing it is because they have their own Analytics code. We should look into this and add it to the exclusion list or fix the issue

**Comment by AlanBCole** [comment]
Taking a look at this issue. It is 'always' in the list of overridden features for me locally.

**Comment by AlanBCole** [comment]
@jwfuller So it looks like cu_googleanalytics becomes overridden in express_settings.module at: 
- https://github.com/CuBoulder/express_mono/blob/deb6a43e3316407bf00268fdee42ef053ac759d5/modules/custom/express_settings/express_settings.module#L442-L468. Since this is our own code

I have no idea if the values being saved are useful, up to date, etc. Perhaps the best way to fix this issue is to add `settings[can_be_overridden] = 1` to cu_googleanalytics.info since it does seem to be deliberately overridden in our code.

**Comment by jwfuller** [comment]
@AlanBCole Great find, that code allows the inclusion of multiple GA codes. If they don't have their own GA code the feature is probably normal. This is okay to be overridden
