### ISSUE TITLE
Evaluate refactoring RAVE integration

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express_mono#616]
The request is blocking for uncached pages, so when RAVE or our connection to RAVE goes down, we go down as well.

**Comment by jcsparks** [comment]
[js_uccs-alerts.js.zip](https://github.com/CuBoulder/express_mono/files/5838529/js_uccs-alerts.js.zip)

This is the JS snippet that would check the Rave feed for an update and inject that into the theme DOM.

**Comment by AlanBCole** [comment]
This needs to be fixed in the repository for the contributed module rave_alerts. I am looking into this now. We maintain that module so I will make changes through drupal.org.

For future reference:
- Get added as maintainer to the RAVE Alerts project on Drupal.org
- Get your git ssh stuff working
- Get set up with a gitlab account
- You should be able to make changes now!

P.S. Some time looking into our org on drupal.org and the projects we maintain would be well spent.

**Comment by AlanBCole** [comment]
For a look at the changes I have made look at this branch in this repo -> https://github.com/CuBoulder/express_mono/tree/feature/616
