### ISSUE TITLE
Replace Compass for Compiling SASS (.scss) Files

### ISSUE THREAD

**Issue by AlanBCole** [CuBoulder/express_mono#767]
As Compass is now largely unmaintained and deprecated we need to come up with a new solution for compiling the .scss files in our express_mono repo. Some ideas are given below:

### Node.js based solutions (requiring Node to be installed, of course):
- gulp.js task runner
    - requires a package.json with gulp and any gulp-scss listed as dev dependencies
    - requires users to run `npm install` to install all dependencies in node_modules folder
    - Probably also requires a script in package.json file to run gulp easily. -> `npm run gulp` or similar 
    - requires a gulpfile.js that defines the tasks to be run.
- npm scripts using node packages directly
    - requires a package.json file with .scss dev dependecies listed
    - requires users to run `npm install` to install all dependencies in node_modules folder
    - requires a script in the package.json file that defines what will be compiled and where, how, etc.
    - simple terminal command `npm run <script name> <possiblySomeOptions>`

### Composer based solutions
- (have not looked at these but thought that Composer should receive at least a mention)

### Other solutions:
- using sass directly in the command line
    - `sass --watch scss/input.scss:css/output.css`
- removing all .scss files and simply use all features of CSS3 specification.

Please provide thoughts and additional solutions that you might have keeping some of the following in mind:
- easy to configure
- few dependencies
- simple to use
- technologies most of us are familiar with, at least a bit
- technologies that are in common use and will likely stay in common use for the foreseeable future

**Comment by jwfuller** [comment]
Want to take a look at our use of SASS to see if we can migrate to pure CSS.

If we cannot go pure CSS3, we want to go down the Gulp path, starting with `gulp-sass` and either `dart-sass` or `node-sass` depending on the best practices.

**Comment by tirazel** [comment]
There are at least three options to perform the actual SASS compilation step:

1) dart-sass (written in Dart, running in a Dart VM)
2) dart-sass (written in Dart, compilied down to pure JS)
3) node-sass (written in Node)

dart-sass is the official implementation, maintained by the SASS project.  As such, it should always be up to date with the latest features.  Dart programs can either be run in a Dart VM, or can be compiled down to pure Javascript.  Dart programs within the Dart VM as opposed to the JS version will in general run an order of magnitude faster.  

node-sass is a Node library which itself wraps around LibSass, a compiled C-library.  As such, it's pretty fast, but comes with a Node dependency, and is essentially just a wrapper.  However, node-sass and LibSass have been deprecated, and should probably be avoided for that reason alone given there are other options.

Comparison:

Option 1, dart-sass in a VM:  
The fastest, official, comes with a Dart dependency.

Option 2, dart-sass compiled to JS:  
The slowest by far, official, seems appealing due to lack of dependencies except for JS, except it's distributed through npm, so you likely end up with a Node dependency anyways.

Option 3, node-sass: 
Pretty fast, deprecated, Node dependency.  Should be avoided on new projects due to deprecation.


Assuming the gulp-sass plugin works with it, and that Dart isn't to hard to set up, Option 1 seems like the best.

**Comment by AlanBCole** [comment]
At this point, I think we should simply go with pure CSS. We already have the compiled css files from scss. I think we can simply modify the css files from here on as needed. Perhaps refactoring etc as needed.

**Comment by AlanBCole** [comment]
Will check with Kevin Crafts to understand original need for .scss and see if CSS is now (in 2021) ready and able to replace it for our use cases.

**Comment by AlanBCole** [comment]
It looks like I spoke too soon. There are a good number of scss features used, particular mixins, that might be a lot of work to replace with 'vanilla' css. Using Gulp/Node might be a simpler option for this use case.

**Comment by AlanBCole** [comment]
@jwfuller @jcsparks It seems like this, adding gulp etc, is a good situation for GitHub action workflows, right? Also, updating this repo's readme.md file would be helpful.

**Comment by AlanBCole** [comment]
## Current state of affairs
I am now using gulp-dart-sass package to compile our .scss files into css. I have now run into the issue that our .scss codebase seems to be using Compass .scss stylesheets which are not found when including them in our .scss stylesheets (via @import statements etc).

#### Things to do:
- [x] Use gulp.watch to react to .scss changes and compile css files on change.
- [x] Add a compileAllScss command to gulpfile.js to compile all .scss files but ignore _*.scss files.
- [x] Find the Compass dependencies needed for our .scss code to work.
    - Found here `/Library/Ruby/Gems/2.6.0/gems/compass-1.0.3/test/fixtures/stylesheets/compass`.
    - I have copied this to our root level directory. Now at -> `express/compass`.
- [ ] Make Compass' internal @import etc statements work. 
    - Right now I am getting the error that files in `compass/css3/**` are not found. There is no css3 directory that I can find.

**Comment by AlanBCole** [comment]
There is some code included in Compass that our scss files depend on. We are putting this issue on hold for now as Compass does work for us at the moment, it is simply not a project being actively maintained at the moment, and the work needed to put into it is not appropriate at the moment.
